name: 'deployaks'

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  bicepdeploy:
    name: 'Storage account Deploment and validation'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4        

      - name: Azure login
        uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep
        uses: Azure/bicep-deploy@v2.3.0
        with:
          type: deployment
          operation: 'validate'
          scope: 'resourceGroup'
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP }}
          bicep-file: '${{ github.workspace }}/bicep/deployment.bicep'
          parameters-file: '${{ github.workspace }}/bicep/environments/dev.bicepparam'

      - name:  Deploy Bicep
        uses: Azure/bicep-deploy@v2.3.0
        with:
          type: deployment
          operation: 'deploy'
          scope: 'resourceGroup'
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          resource-group-name: ${{ vars.AZURE_RESOURCE_GROUP }}
          bicep-file: '${{ github.workspace }}/bicep/deployment.bicep'
          parameters-file: '${{ github.workspace }}/bicep/environments/dev.bicepparam'