name: 'manual-init-env'

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  bicepdeploy:
    name: 'Deploy ACR and set secrets'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - id: bicep-acr-deploy
        uses: nikodemskalski/kubernetes/.github/actions/bicep-deploy-steps@master
        with:
          environment: development
          bicep-file: '${{ github.workspace }}/bicep/ACR/acr.deployment.bicep'
          parameters-file-path: '${{ github.workspace }}/bicep/ACR/environments/dev.bicepparam'
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

      - name: Generate installation token
        id: generate-gh-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: NikodemSkalski
          repositories: |
            devops-labs
            kubernetes
            
      - name: Get ACR Admin Login and Password
        env:
          GH_TOKEN: ${{ steps.generate-gh-token.outputs.token }} 
          ACR_NAME: ${{ fromJSON(steps.bicep-acr-deploy.outputs.deployment-outputs).registryName }}
          ACR_LOGIN_SERVER: ${{ fromJSON(steps.bicep-acr-deploy.outputs.deployment-outputs).registryLoginServer }}
        run: |
          echo "ACR_NAME=$env:ACR_NAME"
          $ACR_ADMIN_USERNAME=$(az acr credential show --name $env:ACR_NAME --query "username" -o tsv)
          if(!$ACR_ADMIN_USERNAME) {
            Write-Host "ACR Admin Username is empty. Exiting."
            exit 1
          }
          $ACR_ADMIN_PASSWORD=$(az acr credential show --name $env:ACR_NAME --query "passwords[0].value" -o tsv)
          if(!$ACR_ADMIN_PASSWORD) {
            Write-Host "ACR Admin Password is empty. Exiting."
            exit 1
          }
          echo "::add-mask::$ACR_ADMIN_USERNAME"
          echo "::add-mask::$ACR_ADMIN_PASSWORD"
          gh variable set ACR_NAME --repo NikodemSkalski/kubernetes --body "$env:ACR_NAME"
          gh variable set ACR_LOGIN_SERVER --repo NikodemSkalski/kubernetes --body "$env:ACR_LOGIN_SERVER"
          gh secret set ACR_ADMIN_USERNAME --repo NikodemSkalski/kubernetes --body "$ACR_ADMIN_USERNAME"
          gh secret set ACR_ADMIN_PASSWORD --repo NikodemSkalski/kubernetes --body "$ACR_ADMIN_PASSWORD"
          gh variable set ACR_NAME --repo NikodemSkalski/devops-labs --body "$env:ACR_NAME"
          gh secret set ACR_ADMIN_USERNAME --repo NikodemSkalski/devops-labs --body "$ACR_ADMIN_USERNAME"
          gh secret set ACR_ADMIN_PASSWORD --repo NikodemSkalski/devops-labs --body "$ACR_ADMIN_PASSWORD"
