name: 'manual-deploy-aks'

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  call-bicep-deploy:
    uses: NikodemSkalski/kubernetes/.github/workflows/templates/workflows/bicep-deploy.yml@master
    with:
      environment: development
      bicep-file: '${{ github.workspace }}/bicep/deployment.bicep'
      parameters-file-path: '${{ github.workspace }}/bicep/environments/dev.bicepparam'

  kubernetesdeploy:
    needs: call-bicep-deploy
    name: 'Deploy AKS'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4        

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set STORAGE_NAME and BLOB_CONTAINER_NAME variables for terraform
        id: set-terraform-vars
        run: |            
            TERRAFORM_STORAGE_NAME=$(az deployment group show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name deployGlobalStorage --query "properties.globalStorageAccount.outputs.storageAccountName.value" -o tsv)
            TERRAFORM_BLOB_CONTAINER_NAME=$(az deployment group show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name deployGlobalStorage --query "properties.globalStorageAccount.outputs.blobContainerName.value" -o tsv)
            Write-Host "STORAGE_NAME=$TERRAFORM_STORAGE_NAME"
            Write-Host "BLOB_CONTAINER_NAME=$TERRAFORM_BLOB_CONTAINER_NAME"
            $expiry = (Get-Date).ToUniversalTime().AddHours(1).ToString("yyyy-MM-ddTHH:mm:ssZ")
            $SAS_TOKEN = az storage container generate-sas --account-name $TERRAFORM_STORAGE_NAME --name $TERRAFORM_BLOB_CONTAINER_NAME --permissions rwdlc --expiry $expiry --https-only
            "::add-mask::$SAS_TOKEN" >> $env:GITHUB_OUTPUT
            "sas=$SAS_TOKEN" >> $env:GITHUB_OUTPUT

      - name: Terraform init
        working-directory: '${{ github.workspace }}/terraform'
        env:
          ARM_SAS_TOKEN: ${{ steps.set-terraform-vars.outputs.sas }}
        run: terraform init                