name: 'manual-deploy-aks'

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  call-bicep-deploy:
    uses: NikodemSkalski/kubernetes/.github/workflows/templates.jobs.bicep-deploy.yml@master
    with:
      environment: development
      bicep-file: '${{ github.workspace }}/bicep/deployment.bicep'
      parameters-file-path: '${{ github.workspace }}/bicep/environments/dev.bicepparam'
      acr-name: ${{ vars.ACR_NAME }}
      acr-admin-username: ${{ vars.ACR_ADMIN_USERNAME }}
      acr-admin-password: ${{ vars.ACR_ADMIN_PASSWORD }}
      azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  kubernetesdeploy:
    needs: call-bicep-deploy
    name: 'Deploy AKS'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4        

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set STORAGE_NAME and BLOB_CONTAINER_NAME variables for terraform
        id: set-terraform-vars
        run: |            
            TERRAFORM_STORAGE_NAME=$(az deployment group show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name deployGlobalStorage --query "properties.globalStorageAccount.outputs.storageAccountName.value" -o tsv)
            TERRAFORM_BLOB_CONTAINER_NAME=$(az deployment group show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name deployGlobalStorage --query "properties.globalStorageAccount.outputs.blobContainerName.value" -o tsv)
            Write-Host "STORAGE_NAME=$TERRAFORM_STORAGE_NAME"
            Write-Host "BLOB_CONTAINER_NAME=$TERRAFORM_BLOB_CONTAINER_NAME"
            $expiry = (Get-Date).ToUniversalTime().AddHours(1).ToString("yyyy-MM-ddTHH:mm:ssZ")
            $SAS_TOKEN = az storage container generate-sas --account-name $TERRAFORM_STORAGE_NAME --name $TERRAFORM_BLOB_CONTAINER_NAME --permissions rwdlc --expiry $expiry --https-only
            "::add-mask::$SAS_TOKEN" >> $env:GITHUB_OUTPUT
            "sas=$SAS_TOKEN" >> $env:GITHUB_OUTPUT
            "state_blob_name=$TERRAFORM_BLOB_CONTAINER_NAME" >> $env:GITHUB_OUTPUT

      - name: Terraform init
        working-directory: '${{ github.workspace }}/terraform/prod'
        env:
          ARM_SAS_TOKEN: ${{ steps.set-terraform-vars.outputs.sas }}
        run: terraform init -backend-config="resource_group_name=${{ vars.AZURE_RESOURCE_GROUP }}"   -backend-config="storage_account_name=${{ vars.STORAGE_ACCOUNT_NAME }}"  -backend-config="container_name=${{ vars.BLOB_CONTAINER_NAME }}" -backend-config="key=${{ steps.set-terraform-vars.outputs.state_blob_name }}" -backend-config="sas_token=${{ steps.set-terraform-vars.outputs.sas }}"

      - name: Terraform plan
        working-directory: '${{ github.workspace }}/terraform/prod'
        env:
          ARM_SAS_TOKEN: ${{ steps.set-terraform-vars.outputs.sas }}
        run: terraform plan -var="aks_name=${{ vars.AKS_NAME }}" -var="resource_group_name=${{ vars.AZURE_RESOURCE_GROUP }}" -var="location=${{ vars.AZURE_LOCATION }}" -var="kubernetes_version=${{ vars.KUBERNETES_VERSION }}" -var="role_based_access_control_enabled=${{ vars.RBAC_AAD_AZURE_RBAC_ENABLED }}" -var="private_dns_zone_id=${{ vars.PRIVATE_DNS_ZONE_ID }}" -var="tags=${{ vars.TAGS }}"
      
      - name: Terraform apply
        working-directory: '${{ github.workspace }}/terraform/prod'
        env:
          ARM_SAS_TOKEN: ${{ steps.set-terraform-vars.outputs.sas }}
        run: terraform apply -auto-approve -var="aks_name=${{ vars.AKS_NAME }}" -var="resource_group_name=${{ vars.AZURE_RESOURCE_GROUP }}" -var="location=${{ vars.AZURE_LOCATION }}" -var="kubernetes_version=${{ vars.KUBERNETES_VERSION }}" -var="role_based_access_control_enabled=${{ vars.RBAC_AAD_AZURE_RBAC_ENABLED }}" -var="private_dns_zone_id=${{ vars.PRIVATE_DNS_ZONE_ID }}" -var="tags=${{ vars.TAGS }}"

