name: 'manual-init-env'

on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  bicepdeploy:
    name: 'Deploy ACR and set secrets'
    runs-on: ubuntu-latest
    environment: development

    steps:
      
      - uses: nikodemskalski/kubernetes/.github/actions/bicep-deploy-steps@master
        with:
          environment: development
          bicep-file: '${{ github.workspace }}/bicep/ACR/acr.deployment.bicep'
          parameters-file-path: '${{ github.workspace }}/bicep/ACR/environments/dev.bicepparam'
          acr-name: ${{ vars.ACR_NAME }}
          acr-admin-username: ${{ vars.ACR_ADMIN_USERNAME }}
          acr-admin-password: ${{ vars.ACR_ADMIN_PASSWORD }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

      - name: Generate installation token
        id: generate-gh-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: NikodemSkalski
          repositories: |
            devops-labs
            kubernetes
            
      - name: Get ACR Admin Login and Password
        env:
          GH_TOKEN: ${{ steps.generate-gh-token.outputs.token }} 
        run: |
          ACR_NAME=$(az deployment group show --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} --name acrDeploymentDev --query "properties.outputs.registryLoginServer.value" -o tsv)
          ACR_ADMIN_USERNAME=$(az acr credential show --name $ACR_NAME --query "username" -o tsv)
          ACR_ADMIN_PASSWORD=$(az acr credential show --name $ACR_NAME --query "passwords[0].value" -o tsv)
          echo "ACR_NAME=$ACR_NAME"
          echo "::add-mask::$ACR_ADMIN_USERNAME"
          echo "::add-mask::$ACR_ADMIN_PASSWORD"
          gh variable set ACR_NAME --repo NikodemSkalski/kubernetes --body "$ACR_NAME"
          gh secret set ACR_ADMIN_USERNAME --repo NikodemSkalski/kubernetes --body "$ACR_ADMIN_USERNAME"
          gh secret set ACR_ADMIN_PASSWORD --repo NikodemSkalski/kubernetes --body "$ACR_ADMIN_PASSWORD"
          gh variable set ACR_NAME --repo NikodemSkalski/devops-labs --body "$ACR_NAME"
          gh secret set ACR_ADMIN_USERNAME --repo NikodemSkalski/devops-labs --body "$ACR_ADMIN_USERNAME"
          gh secret set ACR_ADMIN_PASSWORD --repo NikodemSkalski/devops-labs --body "$ACR_ADMIN_PASSWORD"
