name: 'publishmodules'
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publishmodules:
    name: 'Publish Bicep Modules'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4        
          
      - name: Generate installation token
        id: generate-gh-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: NikodemSkalski
          repositories: infra-modules
          
      - name: Check out my other private repo
        uses: actions/checkout@v4
        with:
            repository: NikodemSkalski/infra-modules
            token: ${{ steps.generate-gh-token.outputs.token }} 
          
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}


      - name: Find and publish Bicep modules
        shell: pwsh
        env:
          ACR_NAME: ${{ vars.ACR_NAME }}
        run: |
          $tag = "${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"
          $modulesRoot = "${{ github.workspace }}/bicep/modules"
          $items = Get-ChildItem -Recurse -Path $modulesRoot -Filter "main.bicep"
          foreach ($item in $items) {
              $parentPath = $item.DirectoryName
              $relativePath = $parentPath.Replace($modulesRoot, "").Replace("\", "/")
              $target = "br:$env:ACR_NAME/$(relativePath):$(tag)"
              az bicep publish --file $item.FullName --target $target --with-source
          }
      
