name: Reusable bicep deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      bicep-file:
        required: true
        type: string
        default: '${{ github.workspace }}/bicep/deployment.bicep'
      parameters-file-path:
        required: true
        type: string
        default: '${{ github.workspace }}/bicep/environments/dev.bicepparam'
      acr-name:
        required: true
        type: string
        default: ''
      azure-resource-group:
        required: true
        type: string
    secrets:
      acr-admin-username:
        required: true
      acr-admin-password:
        required: true
      azure-credentials:
        required: true
      azure-subscription-id:
        required: true

jobs:
  bicepdeploy:
    name: 'Storage account Deploment and validation'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: nikodemskalski/kubernetes/.github/actions/bicep-deploy-steps@master
        with:
          environment: ${{ inputs.environment }}
          bicep-file: '${{ inputs.bicep-file }}'
          parameters-file-path: '${{ inputs.parameters-file-path }}'
          acr-name: ${{ inputs.acr-name }}
          azure-resource-group: ${{ inputs.azure-resource-group }}
          acr-admin-username: ${{ secrets.acr-admin-username }}
          acr-admin-password: ${{ secrets.acr-admin-password }}
          azure-credentials: ${{ secrets.azure-credentials }}
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
